// ═══════════════════════════════════════════════════════════════════════
// 自動生成された型定義（OpenAPI Specification）
// 手動で編集しないでください
// 生成コマンド: just generate-types
// 生成日時: 2026-04-19 20:46:26
// ═══════════════════════════════════════════════════════════════════════

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/mcp/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects Mcp
     * @description List all projects available in TaskForge. Requires authentication.
     */
    get: operations["list_projects_mcp_mcp_projects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/mcp/tasks/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks Mcp
     * @description List all tasks for a specific project by project_id. Requires authentication.
     */
    get: operations["list_tasks_mcp_mcp_tasks__project_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description ユーザー登録エンドポイント（レート制限：5回/分）
     */
    post: operations["register_api_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description ユーザーログインエンドポイント（レート制限：10回/分）
     */
    post: operations["login_api_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description プロジェクト一覧取得（ページネーション付き）
     */
    get: operations["list_projects_api_projects_get"];
    put?: never;
    /**
     * Create Project
     * @description プロジェクト作成
     */
    post: operations["create_project_api_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_projects__project_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Project
     * @description プロジェクト削除（ソフトデリート）
     */
    delete: operations["delete_project_api_projects__project_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/tasks": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tasks
     * @description タスク一覧取得（ページネーション付き）
     */
    get: operations["list_tasks_api_projects__project_id__tasks_get"];
    put?: never;
    /**
     * Create Task
     * @description タスク作成
     */
    post: operations["create_task_api_projects__project_id__tasks_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/tasks/{task_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update Task
     * @description タスク更新
     */
    put: operations["update_task_api_tasks__task_id__put"];
    post?: never;
    /**
     * Delete Task
     * @description タスク削除（ソフトデリート）
     */
    delete: operations["delete_task_api_tasks__task_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/sprints": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Sprints */
    get: operations["list_sprints_api_projects__project_id__sprints_get"];
    put?: never;
    /**
     * Create Sprint
     * @description スプリント作成
     */
    post: operations["create_sprint_api_projects__project_id__sprints_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/sprints/{sprint_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update Sprint
     * @description スプリント更新
     */
    put: operations["update_sprint_api_projects__project_id__sprints__sprint_id__put"];
    post?: never;
    /**
     * Delete Sprint
     * @description スプリント削除（ソフトデリート）
     */
    delete: operations["delete_sprint_api_projects__project_id__sprints__sprint_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/ai/decompose": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Decomposition
     * @description AIタスク分解を非同期で開始
     *     ジョブIDを返し、クライアントはポーリングまたはWebhookで結果を確認
     *
     *     処理時間: 通常10-30秒
     */
    post: operations["start_decomposition_api_projects__project_id__ai_decompose_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/ai/jobs/{job_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Decomposition Status
     * @description AIタスク分解ジョブのステータスを取得
     */
    get: operations["get_decomposition_status_api_ai_jobs__job_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/projects/{project_id}/ai/decompose-sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 同期処理（非推奨）
     * @deprecated
     * @description 【非推奨】AIワークフローを同期的に実行
     *     処理に時間がかかるため、非同期エンドポイントの使用を推奨
     */
    post: operations["decompose_tasks_sync_api_projects__project_id__ai_decompose_sync_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/points/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get My Points
     * @description Get current user's points, achievements, and history.
     */
    get: operations["get_my_points_api_points_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/points/me/add": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Points
     * @description Add points to current user.
     */
    post: operations["add_points_api_points_me_add_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/points/achievements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Achievements
     * @description List all available achievements.
     */
    get: operations["list_achievements_api_points_achievements_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/points/me/achievements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get My Achievements
     * @description Get current user's unlocked achievements.
     */
    get: operations["get_my_achievements_api_points_me_achievements_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/points/leaderboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Leaderboard
     * @description Get top users by points.
     */
    get: operations["get_leaderboard_api_points_leaderboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Users
     * @description 管理者用：全ユーザー一覧を取得
     */
    get: operations["list_users_api_admin_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List All Projects
     * @description 管理者用：全プロジェクト一覧を取得
     */
    get: operations["list_all_projects_api_admin_projects_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/make-admin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Make User Admin
     * @description 管理者用：ユーザーを管理者に昇格
     */
    post: operations["make_user_admin_api_admin_users__user_id__make_admin_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/admin/users/{user_id}/revoke-admin": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke User Admin
     * @description 管理者用：ユーザーの管理者権限を剥奪
     */
    post: operations["revoke_user_admin_api_admin_users__user_id__revoke_admin_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Check
     * @description ヘルスチェック - DBとRedisの接続状態を確認
     */
    get: operations["health_check_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AIDecompositionItem */
    AIDecompositionItem: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Priority
       * @default 2
       */
      priority: number;
      /** Estimate */
      estimate?: number | null;
    };
    /**
     * AIDecompositionJobResponse
     * @description AI分解ジョブ作成応答
     */
    AIDecompositionJobResponse: {
      /**
       * Job Id
       * @description CeleryジョブID
       */
      job_id: string;
      /**
       * Status
       * @description ジョブステータス
       */
      status: string;
      /**
       * Message
       * @description メッセージ
       */
      message: string;
    };
    /** AIDecompositionRequest */
    AIDecompositionRequest: {
      /** Prompt */
      prompt: string;
      /** Sprint Id */
      sprint_id?: number | null;
    };
    /** AIDecompositionResponse */
    AIDecompositionResponse: {
      /** Tasks */
      tasks: components["schemas"]["AIDecompositionItem"][];
    };
    /**
     * AIDecompositionStatusResponse
     * @description AI分解ジョブステータス応答
     */
    AIDecompositionStatusResponse: {
      /**
       * Job Id
       * @description CeleryジョブID
       */
      job_id: string;
      /**
       * Status
       * @description ジョブステータス
       */
      status: string;
      /**
       * Message
       * @description メッセージ
       */
      message: string;
      /**
       * Result
       * @description 結果（完了時）
       */
      result?: {
        [key: string]: unknown;
      } | null;
      /**
       * Meta
       * @description メタ情報
       */
      meta?: {
        [key: string]: unknown;
      } | null;
    };
    /** AchievementResponse */
    AchievementResponse: {
      /** Id */
      id: number;
      /** Key */
      key: string;
      /** Title */
      title: string;
      /** Description */
      description: string;
      /** Points */
      points: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AddPointsRequest */
    AddPointsRequest: {
      /** Points */
      points: number;
      /** Reason */
      reason: string;
      /** Task Id */
      task_id?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** PaginatedResponse[ProjectResponse] */
    PaginatedResponse_ProjectResponse_: {
      /** Items */
      items: components["schemas"]["ProjectResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Has Next */
      has_next: boolean;
      /** Has Prev */
      has_prev: boolean;
    };
    /** PaginatedResponse[TaskResponse] */
    PaginatedResponse_TaskResponse_: {
      /** Items */
      items: components["schemas"]["TaskResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
      /** Has Next */
      has_next: boolean;
      /** Has Prev */
      has_prev: boolean;
    };
    /** PointsHistoryResponse */
    PointsHistoryResponse: {
      /** Id */
      id: number;
      /** Points */
      points: number;
      /** Reason */
      reason: string;
      /** Task Id */
      task_id: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
    };
    /** ProjectResponse */
    ProjectResponse: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Owner Id */
      owner_id: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** SprintCreate */
    SprintCreate: {
      /** Name */
      name: string;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
    };
    /** SprintResponse */
    SprintResponse: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Project Id */
      project_id: number;
      /** Start Date */
      start_date: string | null;
      /** End Date */
      end_date: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskCreate */
    TaskCreate: {
      /** Title */
      title: string;
      /** Description */
      description?: string | null;
      /**
       * Status
       * @default todo
       */
      status: string;
      /**
       * Priority
       * @default 2
       */
      priority: number;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Estimate */
      estimate?: number | null;
      /** Sprint Id */
      sprint_id?: number | null;
    };
    /** TaskResponse */
    TaskResponse: {
      /** Id */
      id: number;
      /** Project Id */
      project_id: number;
      /** Sprint Id */
      sprint_id: number | null;
      /** Title */
      title: string;
      /** Description */
      description: string | null;
      /** Status */
      status: string;
      /** Priority */
      priority: number;
      /** Start Date */
      start_date: string | null;
      /** End Date */
      end_date: string | null;
      /** Estimate */
      estimate: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** TaskUpdate */
    TaskUpdate: {
      /** Title */
      title?: string | null;
      /** Description */
      description?: string | null;
      /** Status */
      status?: string | null;
      /** Priority */
      priority?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** End Date */
      end_date?: string | null;
      /** Estimate */
      estimate?: number | null;
      /** Sprint Id */
      sprint_id?: number | null;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** UserAchievementResponse */
    UserAchievementResponse: {
      /** Id */
      id: number;
      /** Achievement Id */
      achievement_id: number;
      /**
       * Unlocked At
       * Format: date-time
       */
      unlocked_at: string;
      achievement: components["schemas"]["AchievementResponse"];
    };
    /** UserPointsResponse */
    UserPointsResponse: {
      /** User Id */
      user_id: number;
      /** Total Points */
      total_points: number;
      /** Achievements */
      achievements: components["schemas"]["UserAchievementResponse"][];
      /** Points History */
      points_history: components["schemas"]["PointsHistoryResponse"][];
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: number;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Role */
      role: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_projects_mcp_mcp_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_tasks_mcp_mcp_tasks__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  register_api_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_api_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_projects_api_projects_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_ProjectResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_project_api_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_api_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_project_api_projects__project_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_tasks_api_projects__project_id__tasks_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        status?: string | null;
        sprint_id?: number | null;
      };
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedResponse_TaskResponse_"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_task_api_projects__project_id__tasks_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_task_api_tasks__task_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TaskResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_task_api_tasks__task_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        task_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sprints_api_projects__project_id__sprints_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SprintResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_sprint_api_projects__project_id__sprints_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SprintCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SprintResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_sprint_api_projects__project_id__sprints__sprint_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        sprint_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SprintCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SprintResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_sprint_api_projects__project_id__sprints__sprint_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
        sprint_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_decomposition_api_projects__project_id__ai_decompose_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AIDecompositionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AIDecompositionJobResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_decomposition_status_api_ai_jobs__job_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        job_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AIDecompositionStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  decompose_tasks_sync_api_projects__project_id__ai_decompose_sync_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AIDecompositionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AIDecompositionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_my_points_api_points_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPointsResponse"];
        };
      };
    };
  };
  add_points_api_points_me_add_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddPointsRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserPointsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_achievements_api_points_achievements_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AchievementResponse"][];
        };
      };
    };
  };
  get_my_achievements_api_points_me_achievements_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserAchievementResponse"][];
        };
      };
    };
  };
  get_leaderboard_api_points_leaderboard_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_users_api_admin_users_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"][];
        };
      };
    };
  };
  list_all_projects_api_admin_projects_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectResponse"][];
        };
      };
    };
  };
  make_user_admin_api_admin_users__user_id__make_admin_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revoke_user_admin_api_admin_users__user_id__revoke_admin_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
