"""add_soft_delete_to_models

Revision ID: 9c6062785959
Revises: ef5b857ce607
Create Date: 2026-04-17 15:24:57.592436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c6062785959'
down_revision: Union[str, Sequence[str], None] = 'ef5b857ce607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_key'), 'achievement', ['key'], unique=True)
    op.create_table('pointshistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pointshistory_created_at'), 'pointshistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_pointshistory_task_id'), 'pointshistory', ['task_id'], unique=False)
    op.create_index(op.f('ix_pointshistory_user_id'), 'pointshistory', ['user_id'], unique=False)
    op.create_table('userachievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userachievement_achievement_id'), 'userachievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_userachievement_user_id'), 'userachievement', ['user_id'], unique=False)
    op.add_column('project', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_project_deleted_at'), 'project', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=False)
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.add_column('sprint', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_sprint_deleted_at'), 'sprint', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sprint_project_id'), 'sprint', ['project_id'], unique=False)
    op.add_column('task', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_deleted_at'), 'task', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_task_priority'), 'task', ['priority'], unique=False)
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_sprint_id'), 'task', ['sprint_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    op.add_column('user', sa.Column('total_points', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_column('user', 'total_points')
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_sprint_id'), table_name='task')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_index(op.f('ix_task_priority'), table_name='task')
    op.drop_index(op.f('ix_task_deleted_at'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.drop_column('task', 'deleted_at')
    op.drop_index(op.f('ix_sprint_project_id'), table_name='sprint')
    op.drop_index(op.f('ix_sprint_deleted_at'), table_name='sprint')
    op.drop_column('sprint', 'deleted_at')
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_deleted_at'), table_name='project')
    op.drop_column('project', 'deleted_at')
    op.drop_index(op.f('ix_userachievement_user_id'), table_name='userachievement')
    op.drop_index(op.f('ix_userachievement_achievement_id'), table_name='userachievement')
    op.drop_table('userachievement')
    op.drop_index(op.f('ix_pointshistory_user_id'), table_name='pointshistory')
    op.drop_index(op.f('ix_pointshistory_task_id'), table_name='pointshistory')
    op.drop_index(op.f('ix_pointshistory_created_at'), table_name='pointshistory')
    op.drop_table('pointshistory')
    op.drop_index(op.f('ix_achievement_key'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
