"""add_user_role_field

Revision ID: ef5b857ce607
Revises: 834d79f0b33c
Create Date: 2026-02-25 00:23:17.382775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef5b857ce607'
down_revision: Union[str, Sequence[str], None] = '834d79f0b33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. NULLを許可する列を追加
    op.add_column('user', sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # 2. 既存レコードを更新（デフォルト値 'user' を設定）
    op.execute("UPDATE \"user\" SET role = 'user' WHERE role IS NULL")
    
    # 3. NOT NULL制約を追加
    op.alter_column('user', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
